# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbitmq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueinfo',
            name='consumers',
            field=models.CharField(max_length=255, verbose_name='\u6d88\u8d39\u8005\u96c6\u7fa4'),
        ),
        migrations.AlterField(
            model_name='queueinfo',
            name='name',
            field=models.CharField(max_length=255, verbose_name='\u961f\u5217\u540d\u79f0'),
        ),
    ]
